# Generated by Django 4.1.4 on 2023-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_categories_color_filter_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='point1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='point2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='point3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
